version: "3.8"

services:

  app:
    build:
      context: ./backend
      dockerfile: ../docker/go/Dockerfile
    container_name: rotasflex_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: rotasflex_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rotasflex
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: rotasflex_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
